generic-service:
  nameOverride: hmpps-court-data-ingestion-api
  productId: "DPS014" # productId for the product that this belongs too, i.e. DPS001, see README.md for details
  serviceAccountName: hmpps-court-data-ingestion-api

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-court-data-ingestion-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-court-data-ingestion-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-court-data-ingestion-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    sqs-court-data-ingestion-queue-secret:
      HMPPS_SQS_QUEUES_COURTDATAINGESTION_QUEUE_NAME: "sqs_queue_name"
    sqs-court-data-ingestion-dlq-secret:
      HMPPS_SQS_QUEUES_COURTDATAINGESTION_DLQ_NAME: "sqs_queue_name"

  retryDlqCronjob:
    enabled: true

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-court-data-ingestion-api
