---
# Per environment values which override defaults in hmpps-court-data-ingestion-api/values.yaml

generic-service:
  ingress:
    host: court-data-ingestion-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
  businessHoursOnly: true
  sqsAlertsQueueNames:
    - "calculate-release-dates-team-prod-hmpps_court_data_ingestion_queue"
    - "calculate-release-dates-team-prod-hmpps_court_data_ingestion_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
